---
title: "Homework 3"
subtitle: "Research in Health Economics, Spring 2024 https://github.com/riadharnidharka/Econ470HW3"
author: "Ria Dharnidharka"
format:
  pdf:
    output-file: "dharnidharka-r-hwk3-1"
    output-ext:  "pdf"
    header-includes:
      - \usepackage{float}
      - \floatplacement{table}{H}
---
```{r setup, include=FALSE}
knitr::opts_chunk$set(warning = FALSE)
```

```{r}
#| include: false

if (!require("pacman")) install.packages("pacman")
pacman::p_load(tidyverse, ggplot2, dplyr, lubridate, readr, readxl, hrbrthemes, fixest,
               scales, gganimate, gapminder, gifski, png, tufte, plotly, OECD,
               ggrepel, survey, foreign, devtools, pdftools, kableExtra, modelsummary,
               kableExtra)
```
```{r}
#| include: false
#| eval: true

 
load("Hw3_workspace.Rdata")
```
\newpage

\vspace{.2in}
\noindent 1. Present a bar graph showing the proportion of states with a change in their cigarette tax in each year from 1970 to 1985.

```{r}
#| echo: false
#| label: change.tax
#| fig-cap: "States with a Change in Cigarette Tax (1970-1985)"

question1.graph
```
\newpage

\vspace{.2in}
\noindent 2. Plot on a single graph the average tax (in 2012 dollars) on cigarettes and the average price of a pack of cigarettes from 1970 to 2018.